twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # the value is the service's id
        global: '@App\Service\GlobalTwig'
        global2: '@App\Service\GlobalBrands'
    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/public/css': styles
when@test:
    twig:
        strict_variables: true